
development:
  adapter: postgresql
  encoding: unicode
  database: Gastropangs_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: Gastropangs_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: Gastropangs_production
  pool: 5
